## Python Advance: NumPy Basics

![caption](images/numpy-logo.jpg)
***
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. In this part, along with the basics of NumPy such as its architecture and environment, we shall also discuss the various array functions, types of indexing, etc.

We can install numpy by `pip install numpy`

- Main object: **`ndarray`**


# ndarray
***

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. An instance of ndarray class can be constructed by different array creation routines described later.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows −

In [1]:
import numpy
numpy.array

<function numpy.array>


## How do I create Arrays in Python?
***
* Create an array from a regular Python list or tuple using the array function. 

* The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [2]:
import numpy as np

# From list: 1d array
my_list = [10, 20, 30]
np.array(my_list)

array([10, 20, 30])

In [3]:
type(np.array(my_list))

numpy.ndarray

In [4]:
# From list: 2d array
list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
np.array(list_of_lists)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
type(np.array(list_of_lists))

numpy.ndarray

An example of how does n-dimensional looks

## Types

![NumPy Array Types](images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.



## numpy.dtype
***
<br/>
The data type or dtype describes the kind of elements that are contained within the array.

* **bool**: Boolean values
<br/><br/>

* **int**: Integer values. Can be int16, int32, or int64.


* **float**: Floating point values. Can be float16, float32, or float64.
<br/><br/>


* ** string**: Text. Can be string or unicode (this distinction is greatly simplified in Python 3)

## Let's try it ourselves!
***
### Create a vector from the list [10, 20, 30]. Print the dtype and shape.

In [6]:
my_list = [10, 20, 30]

arr = np.array(my_list)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.shape

(3,)

In [11]:
len(arr.shape)

1

In [12]:
list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
twod_array = np.array(list_of_lists)

In [13]:
twod_array.shape

(3, 3)

In [14]:
len(twod_array.shape)

2

In [15]:
my_list = [10, 20, 30]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)

int32
(3,)


In [18]:
lst = [10, 20, 30]
ndarr = np.array(lst)
print(ndarr.dtype)
print(ndarr.shape)

int32
(3,)


# NumPy Built-in methods

## `arange`
***
arange(**[start,]** ***stop[, step,][, dtype]***) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. **[Start, Stop)** (similar to the Python **`range()`** function).

In [20]:
import numpy as np

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## `zeros` and `ones`
***
Generate arrays of all zeros and ones

In [28]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## `linspace`
***
Linspace: Return **evenly spaced** numbers over a specified interval.

    linspace(start, stop, num=50, endpoint=True, retstep=False)

* Will return `num` number of values
* Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop)
* Closed or half-open interval depends on whether 'endpoint' is True or False.

In [34]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [38]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])



## How do I generate Random Numbers?
***
<br/>
Numpy also has lots of ways to create random number arrays of given shape

- **`rand`**:

`numpy.random.rand(d0, d1, …, dn)` Create an array of the given shape and populate it with random samples from a **uniform distribution**

- **`randn`**: 

`numpy.random.randn(d0, d1, …, dn)`creates an array of specified shape and fills it with random values as per **standard normal distribution**.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

- **`randint`**: 

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [39]:
# random number (uniform distribution) array of shape (3 , 4)

np.random.rand(3, 4)

array([[0.55962089, 0.53854744, 0.13993561, 0.65323515],
       [0.47127577, 0.59666261, 0.3894995 , 0.21584826],
       [0.09135213, 0.8721125 , 0.86212303, 0.72295503]])

In [40]:
# random number (standard normal distribution) array of shape (2, 3)

print (np.random.randn(2, 3))

[[-1.06666582  1.26556437  0.15946266]
 [ 0.67349825 -0.04055966 -0.41802622]]


In [41]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

np.random.randint(4, 40, 10)

array([ 8, 21, 25, 36, 27,  7,  8, 30, 18, 25])

In [43]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(4,4))

array([[ 7, 41, 34, 27],
       [ 1, 22, 42, 24],
       [37, 19, 44, 33],
       [ 6, 17, 13, 49]])